from setuptools import find_packages, setup

setup(
    name="eninet",
    version="0.1.0",
    description="ENINet: Molecule Graph Networks with Many-body Equivariant Interactions",
    author="Tsuda Laboratory",
    author_email="zt.mao97@gmail.com",
    url="https://github.com/tsudalab/eninet",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    include_package_data=True,
    install_requires=[
        "torch==2.0.1",
        "torchvision==0.15.2",
        "torchaudio==2.0.2",
        "pytorch-lightning==2.3.3",
        "ase==3.22.1",
        "pymatgen==2023.8.10",
        "numpy==1.22.4",
        "h5py==3.11.0",
        "tqdm==4.64.1",
        "wandb==0.13.4",
        "monty==2022.4.26",
        "scikit-learn==1.0.1",
        "matplotlib==3.5.2",
        "pandas==1.4.4",
        "optuna==3.6.1",
        "fastapi==0.88.0",
        "uvicorn==0.30.3",
        "requests==2.28.1",
    ],
    classifiers=[
        "Programming Language :: Python :: 3.8",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires=">=3.8",
)
